using System.Collections.Generic;
using Assets.Scripts.Ads;
using Assets.Scripts.Enemies.Data;
using Assets.Scripts.Misiles;
using Assets.Scripts.SharedDataModels;
using Assets.Scripts.UI.DataModels;
using Assets.Scripts.Utils;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Assets.Scripts.UI.Menu
{
    public class MainMenuController : MonoBehaviour
    {
        public AutoGeneratedEnemy FastEnemy;
        public AutoGeneratedEnemy TankEnemy;
        public AutoGeneratedEnemy RegularEnemy;
        public Sprite WorldSprite;

        public BasePanel LevelSelectorPanel;
        public BasePanel MainMenuPanel;
        public BasePanel StatsPanel;

        public AdManager AdManager;
        public PurchaseManager PurchaseManager;

        public void Start()
        {           
            // AdManager.RequestBanner();
            AdManager.RunBannerAd();
            // AdManager.RequestInterstitial();
        }
        public void ButtonClick_Play()
        {
            AmplitudeManager.LogOnSelectedLevelsMenu();
            LevelSelectorPanel.OpenPanel();
            MainMenuPanel.ClosePanel();
        }

        public void ButtonClick_Stats()
        {
            MainMenuPanel.ClosePanel();
            StatsPanel.OpenPanel();
        }


        public void ButtonClick_UnlimitedPlay()
        {
            AmplitudeManager.LogOnSelectedUnlimitedMode();
            MainMenuPanel.ClosePanel();
            var levelData = new LevelData
            {
                Enemies = new List<BaseEnemyData>
                {
                    FastEnemy, TankEnemy, RegularEnemy
                },
                Name = "Waves",
                WorldLife = 1000,
                WorldSprite = WorldSprite,
                mode = SharedLevelData.LevelMode.Unlimited
            };

            LocalStorage.SetObject("levelData",levelData.GenerateSharedData());
            SceneManager.LoadScene(sceneName: "SampleLevel",LoadSceneMode.Single);

        }

        public void ButtonClick_BuyAds()
        {
            PurchaseManager.BuyNoAds();
        }
    }
}
