using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;
using Random = System.Random;

namespace Assets.Scripts.Enemies.Data
{
    [CreateAssetMenu(menuName = "AutoGeneratedEnemyData",order = 1)]
    public class AutoGeneratedEnemy : BaseEnemyData
    {
        private float baseWaveDuration = 15;
        private float AddedWaveDuration = 2;

        private Random rand = new Random();
        public int Wave { get; private set; } = 0;

        public void GenerateWave()
        {
            Wave++;

            int MonstersToSpawn = Wave;

            SpawnOrder.Clear();

            float totalWaveDuration = baseWaveDuration + Wave * AddedWaveDuration;

            for (int i = 0; i < MonstersToSpawn; i++)
            {
                SpawnOrder.Add((float) rand.NextDouble() * (totalWaveDuration- AddedWaveDuration));
            }

        }

        public bool HasToBeCreated()
        {
            if (SpawnOrderIndex >= SpawnOrder.Count || Wave == 0)
            {
                ResetTimer();
                GenerateWave();
            }

            if (timer > SpawnOrder[SpawnOrderIndex])
            {
                SpawnOrderIndex++;
                return true;
            }
            return false;
        }
    }
}
